# -*- coding: utf-8 -*-
"""Atividades contextualizadas 1, 2 e 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QtmcueqwFB5I1CbKAKHXR0ed725Mqxpx

Atividade contextualizada 1 - LOKOMAT e ZeroG
"""

LOKOMAT
Iniciar andamento da sessão
Paciente chega ao atendimento na clínica
Se for a primeira sessão:
Realize a avaliação do paciente
Agende o retorno 
Se não, avalie de forma breve o paciente
Observe os resultados das avaliações anteriores
Realize um comparativo de resultados 
Meça o comprimento necessário para o paciente
Selecione o tamanho adequado para o uso do paciente
Coloque o dispositivo posicionado no paciente
Regule os cintos para maior segurança
Se os cintos não estiverem firme
Realize novamente a medição
Se não, coloque o paciente no Lokomat
Confira a firmeza das alças
Ajuste o suporte
Ative o elevador para levantar o paciente
Retire a cadeira de rodas
Instrua que o paciente segure os corrimões laterais
Aproxime o exoesqueleto do paciente
Acople o exoesqueleto ao paciente
Feche o cinto existente para a cintura do paciente
Feche os cintos existentes para os pés do paciente
Ajuste os ângulos da articulação do joelho e cintura do paciente
Confirma a amplitude de movimentos necessários para as pernas
Se estiver insatisfatório, retorne para o ajuste dos ângulos
Se não, regule a intensidade que será utilizada na terapia
Inicie os movimentos de marcha


ZERO G
Paciente chega no consultório
Coloque o cinto de suporte
Regule a firmeza do cinto
Se estiver folgada, regule novamente
Se não, acople o cinto ao ZeroG
Verifique os ganchos no cinto de suporte do equipamento
Conecte os cintos de suporte às próteses do paciente
Ative os dispositivos de proteção do equipamento
Inicie a marcha
Controle a velocidade
Registre o progresso

"""Atividade contextualizada 2 (realizar os comandos para subir os dados no git, realizado)

Atividade Contextualizada 3 - microscópio confocal
"""

FaixaDetector =100#nm
resolucao = '30x30' #pixels escolhidos
angulopedido = 15 
limiteresolucao = 1.45
microscopioreferente= "TAMIC" #modeloescolhido
largura_de_banda = 50 
diodo = 978 
intensmax = 5.22
intensmin = 9.85
Bandascomprimento= 63 
aberturapedida = 40 
aberturaemcirculo = 20 

print("objetivo: receber seus dados de usuário para a configuração do seu microscópio confocal")

FaixaDetector2 =input("faixa do detector aqui")
print("alguma alteração na faixa?",int(faixa_do_detector) != int(faixa_do_detector2))

resolucao2 =input("Insira a resolução")
print("resolução alterada?",str(resolucao) != str(resolucao2))

limiteresolucao2 =input("Insira o limite de resolução")
print("alterações do limite?",float(limite_de_resolucao) != float(limite_de_resolucao2))

intensmax2 =input("Insira o valor da intensidade no ponto mais alto")
print("Houve alteração da intensidade no ponto mais alto?",float(intensmax) != float(intensmax2))

microscopioreferente2 =input("Insira o modelo do microscópio")
print("Houve alteração do modelo do microscópio?",str(modelo_de_microscopio) != str(modelo_de_microscopio2))

banda2 =input("Insira a largura de banda")
print("alterações?",float(banda) != float(banda2))

aberturaemcirculo2 =input("abertura em circulo aqui")
print("abertura alterada?",int(aberturaemcirculo) != int(aberturaemcirculo2))

intensmin2 =input("Insira o valor da intensidade menor")
print("alterações?",int(intensmin) != int(intensmin))

diodo2 =input("Insira o valor do diodo")
print("existem alterações?",float(diodo) != float(diodo))

angulo_incidencia2 =input("Insira o angulo de incidencia")
print("Houve alteração do angulo de incidencia?",float(angulopedido) != float(angulopedido2))
#f
print("As informações digitadas pelo usuário são:")
print("Faixa do detector referente é:", FaixaDetector2)
print("A resolução escolhida é:", resolucao2)
print("O angulo de incidencia escolhido é:", angulopedido2)
print("O limite de resolução escolhido é:", resolucao2)
print("O modelo do microscópio escolhido foi:", microscopioreferente2)
print("A largura de banda escolhida é:", largura_de_banda2)
print("A faixa do diodo escolhida foi:", diodo2)
print("O valor da intensidade maior é:", intensmax2)
print("O valor da intensidade no ponto mais baixo é:", intensmin2)
print("A abertura circular escolhida foi:", aberturaemcirculo2)

primeiraLetra = "tttttttttt"
ultimaLetra = "ssssssssss"

print("Para realizar a calibração horizontal, pressione a primeira letra do seu nome 10 vezes e depois a ultima letra do seu nome 10 vezes")

primeiraLetra_2 = input("Pressione a primeira letra do seu nome 10 vezes e depois aperte enter")
print(str(primeiraLetra) == str(primeiraLetra_2))
ultima_letra2 = input("Pressione a ultima letra do seu nome 10 vezes e depois aperte enter")
print(str(ultimaLetra) == str(ultimaLetra2))

print("Para realizar a calibração horizontal, pressione a segunda letra do seu nome 10 vezes e depois a penultima letra do seu nome 10 vezes")

letra2 = "hhhhhhhhhh"
penultiletra = "yyyyyyyyy"

segundaLetra2 = input("Pressione a primeira letra do seu nome 10 vezes e depois aperte enter")
print(str(segundaLetra) == str(segundaLetra2))
penultima_letra2 = input("Pressione a ultima letra do seu nome 10 vezes e depois aperte enter")
print(str(penultimaLetra) == str(penultimaLetra2))

print("Calibração realizada!")

