# -*- coding: utf-8 -*-
"""Aula6_Emille.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K25XJs_FW4prOTKeEL85NJ97Udb_i_sc
"""

import time

#1)ANESTESIA:
print('Bem-vindo!')
while(True):
  anestesia = int(input('Para iniciar o procedimento, selecione (1) para confirmar que o animal está anestesiado:'))
  if anestesia == 1:
    print('Verificado! Posicione o animal o animal no estereotáxico:')
    break
  else:
    print('Para realização do procedimento, é necessário realizar a sedação do animal anteriormente.')
    print('VERIFIQUE A DOSAGEM CORRETA DE ACORDO COM O PESO DO ANIMAL!')
#2)POSICIONAMENTO:
while(True):
  posicionamento = int(input('O animal está posicionado adequadamente ao extereotáxico0? Selecione: (1) SIM e (0) NÃO:'))
  if posicionamento == 1:
      print('Verificado! Realize a limpeza do campo de trabalho! Para isso, siga os seguintes passos:')
      print('(1)Retire a pelagem que recobre a parte superior da calota craniana;')
      print('(2)Retire os tecidos moles;')
      print('(3)Realize a limpeza final com H2O2 10 volumes.')
      break
  else:
   print('Posicione o animal no exteriotáxico.')
#3) VERIFICAÇÃO:
while(True):
  limpeza = int(input('A limpeza foi concluída? Selecione: (1) SIM (0) NÃO:'))
  if limpeza == 1:
    print('Verificado! Agora é necessário setar o Bregma')
    break
  else:
    print('Realize a limpeza do campo de trabalho! Para isso, siga os seguintes passos:')
    print('(1)Retire a pelagem que recobre a parte superior da calota craniana;')
    print('(2)Retire os tecidos moles;')
    print('(3)Realize a limpeza final com H2O2 10 volumes.')
#PROCEDIMENTO:
#Escolher ponto para fixação dos parafusos**
#> Após este procedimento deve-se escolher um ponto para a fixação de parafusos, de preferência na parte posterior da calota craniana, pois a camada óssea é mais espessa e suporta uma maior profundidade do parafuso. 
#> Obs: Cuidar para não aprofundar muito o parafuso. Com parafusos maiores deve-se dar até 3 voltas no parafuso.
#Posicionar a agulha (devidamente preparada para o tamanho da cânula e que servirá de suporte para a fixação das cânulas) sobre o bregma (ver figura acima). 
#Fazer os cálculos de posicionamento AnteroPosterior (AP), 
#LateroLateral (LL) e DorsoVentral (DV). Os valores utilizados para os cálculos são os valores encontrados nas réguas a partir do posicionamento da agulha.
#>> E. G.: Hipocampo (CA1): Valores hipotéticos para fins de cálculo.
#AP: 6,42 cm 
#LL: 3,23 cm
#DV: 4,2 cm
#Isso significa que estes foram os valores encontrados em cada régua do estereotáxico e se subtrai ou soma a estes, os valores de cada estrutura ou núcleo. CA1: AP - 0,42 cm LL +/- 0,30 cm DV - 0,20 cm.
#AP: 6,42 cm – 0,42 = 6,00
#LL: 3,33 cm + 0,30 = 3,63 / - 0,30 = 3,03  (BILATERAL)
#DV: 4,20 cm – 0,20 = 4,00
print('Para iniciar, verifique se o parafuso foi devidamente inserido:')
while(True):
   posicionamento_parafuso = int(input('Quantas voltas foram dadas pelo parafuso? Selecione: (1) = 3 ou (0) >3'))
   if posicionamento_parafuso == 1: 
      print('Verificado! Para o posicionamento da agulha, iremos mover o braço de acordo com as cordenadas:')
      break
   else:
      print('Continuar avançando o parafuso...')
      time.sleep(3)
      print('Parafuso posicionado corretamente! Três voltas realidas.')
AP = 6.42
LL = 3.33
DV = 4.2
print('Os valores da régua encontrados foram: ')
print('Posicionamento anteroposterior:', AP)
print('Posicionamento laterolateral:', LL)
print('Posicionamento dorsoventral:', DV)
while(True):
   mover_braço = int(input('Selecione a estrutura que deseja encontrar: (1) HIPOCAMPO; (2) OUTRA'))
   hip_AP = 0.42 
   hip_LL= 0.30
   hip_DV = 0.20
   if mover_braço == 1:
     AP = AP - hip_AP
     LL_right = LL + hip_LL
     LL_left = LL - hip_LL
     DV = DV - hip_DV
     print('As coordenadas para a estrutura selecionada são:')
     print('Anteroposterior:', hip_AP)
     print('Laterolateral Diretia:', LL_right, 'Laterolateral Esquerda:', LL_left)
     print('Dorsoventral:', hip_DV)
     break
   else:
     print('Não reconhecemos esta estrutura! Insira as cordenadas referentes à estrutura desejada:')
     inseir_cordenadasAP = float(input('Coordenada anteroposterior:'))
     inseir_cordenadasLLRight = float(input('Coordenada laterolateral direita:'))
     inseir_cordenadasLLleft = float(input('Coordenada laterolateral esquerda:'))
     inseir_cordenadasDV = float(input('Coordenada dorsoventral:'))
     AP_estrutura = AP - inseir_cordenadasAP
     LL_right_estrutura = LL + inseir_cordenadasLLRight
     LL_left_estrutura = LL - inseir_cordenadasLLleft
     DV_estrutura = DV - inseir_cordenadasDV
     print('As coordenadas foram atualizadas!')
     print('Anteroposterior:', AP_estrutura)
     print('Laterolateral Diretia:', LL_right_estrutura, 'Laterolateral Esquerda:', LL_left_estrutura)
     print('Dorsoventral:', DV_estrutura)
     break
#Após estes cálculos feitos é hora de localizar os pontos de inserção das cânulas-guia. 
#Assim que estes pontos forem localizados é necessário fazer furos para a introdução das cânulas-guia.
#A localização destes pontos deve ser definida pelos valores encontrados nos cálculos AnteroPosterior (6,00) e LateroLateral (3,63 e 3,03). 
#Deve-se escolher qual dos hemisférios vai ser colocada a primeira cânula, daí os dois valores para as medidas LL.
while(True):
  hem_cânula = int(input('Em qual hemisfério deseja inserir a cânula? (1) HD (2) HE '))
  if hem_cânula == 1:
    if mover_braço == 1:
       print('Inserir cânula no posicionamento: ', LL_right)
    if mover_braço == 2:
       print('Inserir cânula no posicionamento: ', LL_right_estrutura)
  if hem_cânula == 2:
     if mover_braço == 1:
       print('Inserir cânula no posicionamento: ', LL_left)
     if mover_braço == 2:
       print('Inserir cânula no posicionamento: ', LL_left_estrutura)
  break
else:
  print('Opção não encontrada!')
while(True):
  furar_cranio = int(input('Se deseja iniciar a perfuração do crânio digite (1):'))
  if furar_cranio == 1:
    print('Posicionando à 45 graus de angulação...')
    time.sleep(2)
    print('Braço posicionado!')
    print('Iniciando perfuração...')
    time.sleep(3)
    print('Perfuração realizada!')
    break
  else:
    print('Perfuração não iniciada. Verifique as coordenadas para seguir com o procecimento.')
#Após ter atingido este objetivo, introduza a cânula-guia previamente confeccionada até o valor DorsoVentral (4,00) que foi calculado anteriormente.
while(True):
  cânula_guia1 = int(input('Para confirmar a inserção da cânula-guia, digite (1):'))
  if cânula_guia1 == 1:
    print('Inserindo cânula guia em:', hip_DV or DV_estrutura)
    time.sleep(1)
    print('Cânula-guia inserida!')
    time.sleep(1)
    print('Em caso de presença de sangue ou líquido cefalorraquidiano, utilize papel ou gaze para drena-los!')
    time.sleep(1)
    print('Agora você precisa montar o capacete!')
    time.sleep(1)
    print('Para isso siga os seguintes passos:')
    print('1) Misture o Acrílico Polimerizante com o solvente;')
    print('2) Faça um capacete abrangendo o crânio, a cânula-guia e o parafuso;')
    print('3) Deixe secar até ficar suficientemente rígido;')
    break
  else:
    print('Opção não encontrada!')
#O próximo passo é a fixação da outra cânula-guia. 
#Deve-se levantar levemente o braço do estereotáxico cuidando para que a cânula-guia previamente fixada não se movimente. 
#Logo após, posicionar a agulha sobre o outro ponto de inserção da cânula-guia. Introduzir a cânula-guia até o valor DV (4,00) calculado previamente.
while(True):
  cânula_guia2 = int(input('O capacete está devidamente seco? Em caso afrimativo, digite (1) para fixação da próxima cânula-guia:'))
  if cânula_guia2 == 1:
    print('Inserindo cânula guia em:', hip_DV or DV_estrutura)
    time.sleep(1)
    print('Cânula-guia inserida!')
    time.sleep(1)
    print('Em caso de presença de sangue ou líquido cefalorraquidiano, utilize papel ou gaze para drena-los!')
    time.sleep(1)
    print('Agora você precisa montar o capacete!')
    time.sleep(1)
    print('Para isso siga os seguintes passos:')
    print('1) Misture o Acrílico Polimerizante com o solvente;')
    print('2) Faça um capacete abrangendo o crânio, a cânula-guia e o parafuso;')
    print('3) Deixe secar até ficar suficientemente rígido;')
    break
  else:
    print('Retorne quando o capacete estiver devidamente seco.')
#Deve-se levantar levemente o braço do estereotáxico cuidando para que a cânula-guia previamente fixada não se movimente.
#Acomodar o animal em uma caixa aquecida por uma lâmpada e sem outros animais acordados. 
#Assim que o animal despertar colocá-lo de volta a sua caixa-moradia.
while(True):
  finalização = int(input('Ambos os capacetes estão secos? Em caso afirmativo, digite (1) para confirmar a finalização do procedimento.'))
  if finalização == 1:
    print('Movendo o braço...')
    time.sleep(3)
    print('Levantando o braço...')
    time.sleep(2)
    print('Braço movido!')
    print('Remova o animal e o poscione em uma caixa aquecida por uma lâmpada.')
    print('Não o coloque junto à outros animais!')
    print('Assim que o animal estiver acordado, o devolva para sua caixa-moradia.')
    time.sleep(2)
    print('Procedimento Finalizado!')
    break
  else:
    print('Retorne quando ambos os capacetes estiverem devidamente secos.')

"""# Outras coisas

> Ideias aleatórias:


"""

broca_ligada = False
while(True):
  procedimento= int(input("O que você deseja fazer? (1)Setar o bregma , (2)Mover o braço, (3)Ligar/Desligar broca"))
  if procedimento == 2:
    print('Informe as coordenadas para mover o braço:')
    dv = float(input('qual a coordenada DV?'))
    ap = float(input('qual a coordenada AP?'))
    ml = float(input('qual a coordenada ML?'))
    print('Braço movido para as coordenadas DV:{} , AP:{}, ML:{}'.format(dv,ap,ml))
  if procedimento == 3:
    if broca_ligada == False:
      print('Ligando a broca...')
      time.sleep(2)
      broca_ligada = True
      print('Broca LIGADA')
    else:
      print('Desligando a broca...')
      time.sleep(2)
      broca_ligada = False
      print('Broca DESLIGADA')

#1)ANESTESIA:
print('Bem-vindo!')
while(True):
  anestesia = int(input('Para iniciar o procedimento, selecione (1) para confirmar que o animal está anestesiado:'))
  if anestesia == 1:
    print('Verificado! Posicione o animal o animal no estereotáxico:')
    break
  else:
    print('Para realização do procedimento, é necessário realizar a sedação do animal anteriormente.')
    print('VERIFIQUE A DOSAGEM CORRETA DE ACORDO COM O PESO DO ANIMAL!')
#2)POSICIONAMENTO:
while(True):
  posicionamento = int(input('O animal está posicionado adequadamente ao extereotáxico0? Selecione: (1) SIM e (0) NÃO:'))
  if posicionamento == 1:
      print('Verificado! Realize a limpeza do campo de trabalho! Para isso, siga os seguintes passos:')
      print('(1)Retire a pelagem que recobre a parte superior da calota craniana;')
      print('(2)Retire os tecidos moles;')
      print('(3)Realize a limpeza final com H2O2 10 volumes.')
      break
  else:
   print('Posicione o animal no exteriotáxico.')
#3) VERIFICAÇÃO:
while(True):
  limpeza = int(input('A limpeza foi concluída? Selecione: (1) SIM (0) NÃO:'))
  if limpeza == 1:
    print('Verificado! Agora é necessário setar o Bregma')
    break
  else:
    print('Realize a limpeza do campo de trabalho! Para isso, siga os seguintes passos:')
    print('(1)Retire a pelagem que recobre a parte superior da calota craniana;')
    print('(2)Retire os tecidos moles;')
    print('(3)Realize a limpeza final com H2O2 10 volumes.')
#PROCEDIMENTO:
#Escolher ponto para fixação dos parafusos**
#> Após este procedimento deve-se escolher um ponto para a fixação de parafusos, de preferência na parte posterior da calota craniana, pois a camada óssea é mais espessa e suporta uma maior profundidade do parafuso. 
#> Obs: Cuidar para não aprofundar muito o parafuso. Com parafusos maiores deve-se dar até 3 voltas no parafuso.
#Posicionar a agulha (devidamente preparada para o tamanho da cânula e que servirá de suporte para a fixação das cânulas) sobre o bregma (ver figura acima). 
#Fazer os cálculos de posicionamento AnteroPosterior (AP), 
#LateroLateral (LL) e DorsoVentral (DV). Os valores utilizados para os cálculos são os valores encontrados nas réguas a partir do posicionamento da agulha.
#>> E. G.: Hipocampo (CA1): Valores hipotéticos para fins de cálculo.
#AP: 6,42 cm 
#LL: 3,23 cm
#DV: 4,2 cm
#Isso significa que estes foram os valores encontrados em cada régua do estereotáxico e se subtrai ou soma a estes, os valores de cada estrutura ou núcleo. CA1: AP - 0,42 cm LL +/- 0,30 cm DV - 0,20 cm.
#AP: 6,42 cm – 0,42 = 6,00
#LL: 3,33 cm + 0,30 = 3,63 / - 0,30 = 3,03  (BILATERAL)
#DV: 4,20 cm – 0,20 = 4,00
print('Para iniciar, verifique se o parafuso foi devidamente inserido:')
while(True):
   posicionamento_parafuso = int(input('Quantas voltas foram dadas pelo parafuso? Selecione: (1) = 3 ou (0) >3'))
   if posicionamento_parafuso == 1: 
      print('Verificado! Para o posicionamento da agulha, iremos mover o braço de acordo com as cordenadas:')
      break
   else:
      print('Continuar avançando o parafuso...')
      time.sleep(3)
      print('Parafuso posicionado corretamente! Três voltas realidas.')
AP = 6.42
LL = 3.33
DV = 4.2
print('Os valores da régua encontrados foram: ')
print('Posicionamento anteroposterior:', AP)
print('Posicionamento laterolateral:', LL)
print('Posicionamento dorsoventral:', DV)
while(True):
   mover_braço = int(input('Selecione a estrutura que deseja encontrar: (1) HIPOCAMPO; (2) OUTRA'))
   hip_AP = 0.42 
   hip_LL= 0.30
   hip_DV = 0.20
   if mover_braço == 1:
     AP = AP - hip_AP
     LL_right = LL + hip_LL
     LL_left = LL - hip_LL
     DV = DV - hip_DV
     print('As coordenadas para a estrutura selecionada são:')
     print('Anteroposterior:', hip_AP)
     print('Laterolateral Diretia:', LL_right, 'Laterolateral Esquerda:', LL_left)
     print('Dorsoventral:', hip_DV)
     break
   else:
     print('Não reconhecemos esta estrutura! Insira as cordenadas referentes à estrutura desejada:')
     inseir_cordenadasAP = float(input('Coordenada anteroposterior:'))
     inseir_cordenadasLLRight = float(input('Coordenada laterolateral direita:'))
     inseir_cordenadasLLleft = float(input('Coordenada laterolateral esquerda:'))
     inseir_cordenadasDV = float(input('Coordenada dorsoventral:'))
     AP_estrutura = AP - inseir_cordenadasAP
     LL_right_estrutura = LL + inseir_cordenadasLLRight
     LL_left_estrutura = LL - inseir_cordenadasLLleft
     DV_estrutura = DV - inseir_cordenadasDV
     print('As coordenadas foram atualizadas!')
     print('Anteroposterior:', AP_estrutura)
     print('Laterolateral Diretia:', LL_right_estrutura, 'Laterolateral Esquerda:', LL_left_estrutura)
     print('Dorsoventral:', DV_estrutura)
     break
#Após estes cálculos feitos é hora de localizar os pontos de inserção das cânulas-guia. 
#Assim que estes pontos forem localizados é necessário fazer furos para a introdução das cânulas-guia.
#A localização destes pontos deve ser definida pelos valores encontrados nos cálculos AnteroPosterior (6,00) e LateroLateral (3,63 e 3,03). 
#Deve-se escolher qual dos hemisférios vai ser colocada a primeira cânula, daí os dois valores para as medidas LL.
while(True):
  hem_cânula = int(input('Em qual hemisfério deseja inserir a cânula? (1) HD (2) HE '))
  if hem_cânula == 1:
    print('Inserir cânula no posicionamento (ssssssssssss): ', LL_right)
  if hem_cânula == 2:
    print('Inserir cânula no posicionamento:(nnnnnnnnnnnnnnnnnnnnnnnnn) ', LL_left)
    break
else:
  print('Opção não encontrada!')
while(True):
  furar_cranio = int(input('Se deseja iniciar a perfuração do crânio digite (1):'))
  if furar_cranio == 1:
    print('Posicionando à 45 graus de angulação...')
    time.sleep(2)
    print('Braço posicionado!')
    print('Iniciando perfuração...')
    time.sleep(3)
    print('Perfuração realizada!')
    break
  else:
    print('Perfuração não iniciada. Verifique as coordenadas para seguir com o procecimento.')
#Após ter atingido este objetivo, introduza a cânula-guia previamente confeccionada até o valor DorsoVentral (4,00) que foi calculado anteriormente.
while(True):
  cânula_guia1 = int(input('Para confirmar a inserção da cânula-guia, digite (1):'))
  if cânula_guia1 == 1:
    print('Inserindo cânula guia em:', hip_DV or DV_estrutura)
    time.sleep(1)
    print('Cânula-guia inserida!')
    time.sleep(1)
    print('Em caso de presença de sangue ou líquido cefalorraquidiano, utilize papel ou gaze para drena-los!')
    time.sleep(1)
    print('Agora você precisa montar o capacete!')
    time.sleep(1)
    print('Para isso siga os seguintes passos:')
    print('1) Misture o Acrílico Polimerizante com o solvente;')
    print('2) Faça um capacete abrangendo o crânio, a cânula-guia e o parafuso;')
    print('3) Deixe secar até ficar suficientemente rígido;')
    break
  else:
    print('Opção não encontrada!')
#O próximo passo é a fixação da outra cânula-guia. 
#Deve-se levantar levemente o braço do estereotáxico cuidando para que a cânula-guia previamente fixada não se movimente. 
#Logo após, posicionar a agulha sobre o outro ponto de inserção da cânula-guia. Introduzir a cânula-guia até o valor DV (4,00) calculado previamente.
while(True):
  cânula_guia2 = int(input('O capacete está devidamente seco? Em caso afrimativo, digite (1) para fixação da próxima cânula-guia:'))
  if cânula_guia2 == 1:
    print('Inserindo cânula guia em:', hip_DV or DV_estrutura)
    time.sleep(1)
    print('Cânula-guia inserida!')
    time.sleep(1)
    print('Em caso de presença de sangue ou líquido cefalorraquidiano, utilize papel ou gaze para drena-los!')
    time.sleep(1)
    print('Agora você precisa montar o capacete!')
    time.sleep(1)
    print('Para isso siga os seguintes passos:')
    print('1) Misture o Acrílico Polimerizante com o solvente;')
    print('2) Faça um capacete abrangendo o crânio, a cânula-guia e o parafuso;')
    print('3) Deixe secar até ficar suficientemente rígido;')
    break
  else:
    print('Retorne quando o capacete estiver devidamente seco.')
#Deve-se levantar levemente o braço do estereotáxico cuidando para que a cânula-guia previamente fixada não se movimente.
#Acomodar o animal em uma caixa aquecida por uma lâmpada e sem outros animais acordados. 
#Assim que o animal despertar colocá-lo de volta a sua caixa-moradia.
while(True):
  finalização = int(input('Ambos os capacetes estão secos? Em caso afirmativo, digite (1) para confirmar a finalização do procedimento.'))
  if finalização == 1:
    print('Movendo o braço...')
    time.sleep(3)
    print('Levantando o braço...')
    time.sleep(2)
    print('Braço movido!')
    print('Remova o animal e o poscione em uma caixa aquecida por uma lâmpada.')
    print('Não o coloque junto à outros animais!')
    print('Assim que o animal estiver acordado, o devolva para sua caixa-moradia.')
    time.sleep(2)
    print('Procedimento Finalizado!')
    break
  else:
    print('Retorne quando ambos os capacetes estiverem devidamente secos.')