# -*- coding: utf-8 -*-
"""Aula5_Emille

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pqloUuhsNAcb4R0OSFUEi2dBWR1DaKLt
"""

estados=["Acre ","Amapá","Amazonas","Rondônia","Roraima","Tocantins","Pará","Alagoas ","Bahia","Ceará ","Maranhão","Paraíba","Pernambuco",
"Piauí","Rio Grande do Norte","Sergipe","Rio de Janeiro","São Paulo ","Espírito Santo","Minas Gerais",
"Rio Grande do Sul","Santa Catarina","Paraná","Distrito Federal","Goiás","Mato Grosso","Mato Grosso do Sul"]
populacao=[881935,845731,4144597,1777225,605761,1572866,8602865,3337357,14873064,9132078,7075181,40181127,9557071,3273227,3506853,2298696,
17264943,45919049,4018650,21168791,11377239,7164788,11433957,3015268,7018354,3484466,2778986]
ocorridos =[22605,39703,112263,48232,39665,37856,178375,72938,217115,137408,198202,96223,113183,66315,57720,68313,
194651,702665,100859,175715,98007,121666,1275,138735,102665,74509,37425]
casos_novos=[57,185,351,42,365,867,406,204,1085,555,583,190,225,237,178,316,372,3172,1279,1331,130,786,
1275,2268,1073,1240,589]
obitos_totais =[582,617,3505,568,1017,516,5945,1763,4475,3277,8163,2183,7210,1619,2081,1717,14566,26899,2908,4223,
2744,1839,2733,2042,2336,2368,640]
new_obtos =[6,4,22,0,0,5,5,10,69,13,30,21,22,11,14,12,4,47,33,91,55,42,42,66,14,28,14]
roraima = ["Amajari","Alto Alegre","Boa Vista","Bonfim","Cantá","Mucajaí","Normandia","Pacaraima","Uiramutã",
"caracaraí","Caroebe","Rorainopólis","São João da Baliza","São Luiz","Iracema"]

print('Obitos no RJ: ',obitosAcumulados[16])
print(obitosAcumulados)
print('Obitos na paraiba -10: ',obitosAcumulados[11]-10)

len(estado_municipios)

NovosObitos=[3,31,0,6,6,4,5,6,5,0]
print(max(NovosObitos))
print(min(NovosObitos))
estado_municipio={'rj':'Rio de janeiro',
                  'RN':'Natal',
                  'SP':'São Paulo',
                  'Ceará':'Fortaleza',
                  'Pará':'Belém',
                  }