# -*- coding: utf-8 -*-
"""Aula 4 - Emille

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16VWGNAS0FjDG0as3S0Iz_um2uX9rNy86
"""

print('bem-vido')
habituacao=int(input('Realizou habituação? Digite 1) para SIM'))
  if habituacao == 1:
    print('Verificado!')
  else: 
    print('Digito incorreto')
var1=30
movimento_animal=float(input('O animal realizou movimento de aproximação? Digite o valor referente à nova distância: '))
if modelo_animal>var1:
  print('Recompensa liberada!')
else: 
  print('Não reconhecido')
barra=int(input('Adicione a quantidade de vezes que o animal tocou a barra:))
if barra>=20:
  print('proxima fase')
else:
  print('Não reconhecido')
som1=int(input('O animal tocou a barra após a saída de som? Dite 1) para SIM'))
if som == '1':
  print('Recompensa liberada!')
else:
  print('não foi possível liberar recompensa')
exp=int(input('Se passaram 3o minturos! Quantas vezes foi realizado experimento?'))
if exp>='50':
  print('Proxima fase do experimento:')
else:
  print('É necessário continuar...')