# -*- coding: utf-8 -*-
"""AtividadeContextualizadaAula06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dJlQrOaDxQ6vllk6Hx_nuHa1TiMwZ4Lz
"""

while(True):
  peso=int(input('Insira o peso do animal:'))
  anestesia=int(input('Insira quantos mls de anestesia foi aplicado:'))
  finalizar=input('deseja finalizar esta etapa?(s/n)')
  if finalizar=='s':
    break
  else:
    continue

while(True):
 posicao=input('O bregma está corretamente posicionado?(s/n)')
 if posicao=='n':
   print('Barras de suporte estão sendo posicionadas')
   print('verificar a angulação da cabeça')
   break
 elif posicao=='s':
   break

while(True):
  limpeza=input('Foi realizada a tricotomia?(s/n)')
  incisao=input('Foi realizada a incisão?(s/n)')
  if limpeza=='s' and incisao=='s':
    for i in range(10):
      print('Volume de ',i+1,' H2O2 Aplicado')
    print('aplicação de poliacrilato efetivada')
    break  
  else:
    print('confirme as informações quando estiver terminado a etapa:')
    continue

coordenadas={
    'AP':6.42,
    'LL':3.23,
    'DV':4.2
}
print(coordenadas)
calculo=(coordenadas['AP']-0.42,coordenadas['LL']+0.3,
                   coordenadas['DV']-0.2)
print(calculo)
coordenadax=float(input('insira a coordenada x:'))
coordenadaz=float(input('insira a coordenada z:'))

print('coordenadas dos pontos:')
print('anteroposterior = 6.00 e laterolateral = 3.63 e 3.03')
hemisferio=input('qual hemisferio sera colocada a canula?D/E')

print('Perfuração')
for i in range(0,46,5):
  if i<45:
    print('Ajustando angulo: ',i,'º')
  elif i==45:
    print('Angulo ajustado: ',i,'º')
print('introduzindo a canula com um valor de Dorsoventral (4,00)')
print('limpeza da região para a retirada do cranio')

for i in range(6):
  print(i)
